###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/
# Set the path to the wallpaper
$wallpaper = ~/Pictures/wallpapers/spiderverse.jpeg

# Set programs that you use
$terminal = kitty
$fileManager = thunar
$menu = rofi -show drun
$picker = hyprpicker -a
$browser = firefox
$lockscreen = hyprlock
$pomodoro = pilorama
$notificationMenu = swaync-client -t -sw
$logoutMenu = wlogout
