##############################
### WINDOWS AND WORKSPACES ###
##############################
# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Ignore maximize requests from apps.
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0, no_focus on

# App workspace assignments
windowrule = workspace 10, match:class Spotify
windowrule = workspace 9, match:class thunderbird
windowrule = workspace special:magic, match:class com.somehumans.pilorama
