--###############
--## MONITORS ###
--###############

-- See https://wiki.hypr.land/Configuring/Monitors/
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080",
    position = "auto",
    scale = "1",
})

--############################
--## ENVIRONMENT VARIABLES ###
--############################

-- See https://wiki.hypr.land/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

--##################
--## PERMISSIONS ###
--##################

-- See https://wiki.hypr.land/Configuring/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- ecosystem {
--   enforce_permissions = 1
-- }

-- permission = /usr/(bin|local/bin)/grim, screencopy, allow
-- permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
-- permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

-- Source: ~/.config/hypr/configs/defaults.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("configs.defaults")
-- Source: ~/.config/hypr/configs/autostart.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("configs.autostart")
-- Source: ~/.config/hypr/configs/theme.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("configs.theme")
-- Source: ~/.config/hypr/configs/input.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("configs.input")
-- Source: ~/.config/hypr/configs/keybinds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("configs.keybinds")
-- Source: ~/.config/hypr/configs/windows.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("configs.windows")
