--################
--## AUTOSTART ###
--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:

-- exec-once = $terminal
-- exec-once = nm-applet &
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.on("hyprland.start", function()
    hl.exec_cmd("waybar &")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("hyprsunset")
    hl.exec_cmd("wal -R &")
    hl.exec_cmd("swaync")
    hl.exec_cmd("swayosd-server -s ~/.config/swayosd/style.css &")
    -- clipboard history + keep contents alive after the source app closes
    hl.exec_cmd("wl-paste --type text --watch cliphist store &")
    hl.exec_cmd("wl-paste --type image --watch cliphist store &")
    hl.exec_cmd("wl-clip-persist --clipboard regular &")
    hl.exec_cmd("spotify")
    hl.exec_cmd("firefox")
end)

