--#############################
--## WINDOWS AND WORKSPACES ###
--#############################
-- See https://wiki.hypr.land/Configuring/Window-Rules/ for more
-- See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

-- Ignore maximize requests from apps.
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

-- Fix some dragging issues with XWayland
hl.window_rule({
    match = {
        class = "^$",
        title = "^$",
        xwayland = 1,
        float = 1,
        fullscreen = 0,
        pin = 0,
    },
    no_focus = true,
})

-- App workspace assignments
hl.window_rule({
    match = {
        class = "Spotify",
    },
    workspace = "10",
})

hl.window_rule({
    match = {
        class = "thunderbird",
    },
    workspace = "9",
})

hl.window_rule({
    match = {
        class = "com.somehumans.pilorama",
    },
    workspace = "special:magic",
})

