--#############################
--## WINDOWS AND WORKSPACES ###
--#############################
-- See https://wiki.hypr.land/Configuring/Window-Rules/ for more
-- See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

-- Ignore maximize requests from apps.
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

-- Fix some dragging issues with XWayland
hl.window_rule({
    match = {
        class = "^$",
        title = "^$",
        xwayland = 1,
        float = 1,
        fullscreen = 0,
        pin = 0,
    },
    no_focus = true,
})

-- App workspace assignments
hl.window_rule({
    match = {
        class = "Spotify",
    },
    workspace = "10",
})

hl.window_rule({
    match = {
        class = "thunderbird",
    },
    workspace = "9",
})

hl.window_rule({
    match = {
        class = "com.somehumans.pilorama",
    },
    workspace = "special:magic",
})

-- Slide the swaync control center in from the right (it's anchored
-- top+right in swaync/config.json) instead of the global "layers" fade
-- used by every other layer-shell surface (waybar, swayosd, rofi).
hl.layer_rule({
    match = {
        namespace = "^swaync-control-center$",
    },
    -- Force the right edge: without an explicit edge, Hyprland picks
    -- whichever screen edge the panel's center is closest to, which for
    -- a corner-anchored panel like this one was resolving to "top".
    animation = "slide right",
})

