$wallpaper = {{ wallpaper }}

$foreground = rgba({{ foreground | rgb }},{{ alpha_dec }})
$background = rgba({{ background | rgb }},{{ alpha_dec }})

$color0 = rgba({{ color0 | rgb }},{{ alpha_dec }})
$color1 = rgba({{ color1 | rgb }},{{ alpha_dec }})
$color2 = rgba({{ color2 | rgb }},{{ alpha_dec }})
$color3 = rgba({{ color3 | rgb }},{{ alpha_dec }})
$color4 = rgba({{ color4 | rgb }},{{ alpha_dec }})
$color5 = rgba({{ color5 | rgb }},{{ alpha_dec }})
$color6 = rgba({{ color6 | rgb }},{{ alpha_dec }})
$color7 = rgba({{ color7 | rgb }},{{ alpha_dec }})
$color8 = rgba({{ color8 | rgb }},{{ alpha_dec }})
$color9 = rgba({{ color9 | rgb }},{{ alpha_dec }})
$color10 = rgba({{ color10 | rgb }},{{ alpha_dec }})
$color11 = rgba({{ color11 | rgb }},{{ alpha_dec }})
$color12 = rgba({{ color12 | rgb }},{{ alpha_dec }})
$color13 = rgba({{ color13 | rgb }},{{ alpha_dec }})
$color14 = rgba({{ color14 | rgb }},{{ alpha_dec }})
$color15 = rgba({{ color15 | rgb }},{{ alpha_dec }})
